<<<<<<< HEAD
=======

>>>>>>> fdaf099a7e7d5e4a10af31425de04a3ed47da03c
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace kdh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public int Questionsid { get; set; }
        public string Answer1 { get; set; }
        public string Sender_mail { get; set; }
        public System.DateTime Create_date { get; set; }
    
        public virtual Question Question { get; set; }
    }
=======

namespace kdh.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Answer
{

    public int Id { get; set; }

    public int Questionsid { get; set; }

    public string Answer1 { get; set; }

    public string Sender_mail { get; set; }

    public System.DateTime Create_date { get; set; }



    public virtual Question Question { get; set; }

}

>>>>>>> fdaf099a7e7d5e4a10af31425de04a3ed47da03c
}
