

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace kdh.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class HospitalContext : DbContext
{
    public HospitalContext()
        : base("name=HospitalContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Applicant> Applicants { get; set; }

    public virtual DbSet<department> departments { get; set; }

    public virtual DbSet<DirtyWord> DirtyWords { get; set; }

    public virtual DbSet<Doctor> Doctors { get; set; }

    public virtual DbSet<DonateCreditCard> DonateCreditCards { get; set; }

    public virtual DbSet<DonationContact> DonationContacts { get; set; }

    public virtual DbSet<FAQ> FAQs { get; set; }

    public virtual DbSet<Job> Jobs { get; set; }

    public virtual DbSet<LabReport> LabReports { get; set; }

    public virtual DbSet<OnlineConsultationForm> OnlineConsultationForms { get; set; }

    public virtual DbSet<Patient> Patients { get; set; }

    public virtual DbSet<Purpos> Purposes { get; set; }

    public virtual DbSet<Result> Results { get; set; }

    public virtual DbSet<Survey> Surveys { get; set; }

    public virtual DbSet<Testimonial> Testimonials { get; set; }

    public virtual DbSet<TestType> TestTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }

    public virtual DbSet<Answer> Answers { get; set; }

    public virtual DbSet<JobManager> JobManagers { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

}

}

