--INSERT INTO FAQs(Question, Answer, AuthorFirstName, AuthorityFirstName, PurposeId) 
--values('donation', 'online', 'gurinder', 'manager', '201');
--INSERT INTO Purposes(PurposeToCreate) VALUES( 'other');
--delete from FAQs;
--delete from Purposes;
--select * from Purposes;